DATASET:
  INPUT_SIZE: (24,24)
MODEL:
  N_LAYERS: 2
  IN_CHANNELS: 1
  N_FEATURES: 32
OPTIM:
  BATCH_SIZE: 32
  BASE_LR: 0.0005
  DISC_LR: 0.00005
EXP_NAME: 'mnist_test'
LOSS:
  REC_LOSS: 'BCE'
  REC_LOSS_COEFF: 1.
  PRIOR_LOSS_COEFF: 0.1
  ADV_LOSS_COEFF: 0.5