DATASET:
  INPUT_SIZE: (24,24)
MODEL:
  N_LAYERS: 2
  IN_CHANNELS: 1
  N_FEATURES: 64
OPTIM:
  BATCH_SIZE: 32
EXP_NAME: 'mnist_test'
LOSS:
  REC_LOSS: 'BCE'
  REC_LOSS_COEFF: 1
  PRIOR_LOSS_COEFF: 0.005
  ADV_LOSS_COEFF: 2